# --- CONFIGURACIÓN HÍBRIDA (NUBE / LOCAL) ---
# Si existe la variable de entorno DB_URL (en la nube), la usa.
# Si no existe, usa localhost (en tu PC).

# URL de la Base de Datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cargahub_db}

# Usuario (Usa DB_USERNAME o 'postgres' por defecto)
spring.datasource.username=${DB_USERNAME:postgres}

# Contraseña (Usa DB_PASSWORD o '123456' por defecto)
spring.datasource.password=${DB_PASSWORD:123456}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto (Render nos asigna uno dinámicamente en la variable PORT)
server.port=${PORT:8080}
# API Base Path (opcional, pero buena práctica)
server.servlet.context-path=/